name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0/10 * * * *'
  push:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: renovatebot/github-action@v39.0.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate-config.js
