name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0/5 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: renovatebot/github-action@v38.1.11
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate-config.js
          useSlim: false
